# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          #  - repo
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tristengoodz
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_timezone: America/Chicago
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 1000
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_calendar: yes
          plugin_calendar_limit: 5
          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: python
          plugin_code_lines: 30
          plugin_code_load: 10
          plugin_code_visibility: public
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 60000
          plugin_habits_facts: yes
          plugin_habits_from: 100000
          plugin_habits_languages_limit: 20
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60000
          plugin_languages_analysis_timeout_repositories: 20000
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth_custom: tristengoodz/pysura
          plugin_languages_limit: 200
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 6000
          plugin_languages_recent_load: 300000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 300000
          plugin_lines_sections: base
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_repositories: yes
          plugin_repositories_featured: tristengoodz/pysura
          plugin_repositories_order: featured, pinned, starred, random
          plugin_rss: yes
          plugin_rss_limit: 10
          plugin_rss_source: https://pypi.org/rss/project/pysura/releases.xml
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 100
          plugin_starlists_limit_languages: 20
          plugin_starlists_limit_repositories: 10
          plugin_starlists_shuffle_repositories: yes
          plugin_traffic: yes
          repositories_forks: yes
